name: flutter_fullpdfview
description: A Flutter plugin that provides a PDFView widget on Android and iOS.
version: 1.0.0+10
author: arnaudelub <arnaudelub@gmail.com>
homepage: https://github.com//arnaudflutter_pdfview

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.endigo.plugins.pdfviewflutter
    iosPrefix: FLT
    pluginClass: PDFViewFlutterPlugin
